# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Discount Spotlight"
client_id = "84c340413d584409f4055aea77e7b477"
application_url = "https://pig-striking-snipe.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,read_products,write_pixels,read_customer_events"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://pig-striking-snipe.ngrok-free.app/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/auth/shopify/callback",
  "https://pig-striking-snipe.ngrok-free.app/api/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
