# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77ab0f117b5c21f97449cc51920fad19"
name = "LM Discount Dazzle"
application_url = "https://nodejs.luckimediadevelopment.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ds-develop-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,read_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://legitimate-consequences-tan-cubic.trycloudflare.com/auth/callback",
  "https://legitimate-consequences-tan-cubic.trycloudflare.com/auth/shopify/callback",
  "https://legitimate-consequences-tan-cubic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://pig-striking-snipe.ngrok-free.app/api/webhooks/customer_deletion"
  customer_data_request_url = "https://pig-striking-snipe.ngrok-free.app/api/webhooks/customer_request"
  shop_deletion_url = "https://pig-striking-snipe.ngrok-free.app/api/webhooks/deletion"

[pos]
embedded = false
