# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Tealium Track App"
client_id = "c2e807fb42216f62e995852d94a144e8"
application_url = "https://pig-striking-snipe.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true 

[auth]
redirect_urls = [
  "https://pig-striking-snipe.ngrok-free.app/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/auth/shopify/callback",
  "https://pig-striking-snipe.ngrok-free.app/api/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lm-ai-seo-metatag-enhancer-store.myshopify.com"
