# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Discount Spotlight"
client_id = "77ab0f117b5c21f97449cc51920fad19"
application_url = "https://pig-striking-snipe.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_price_rules"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://pig-striking-snipe.ngrok-free.app/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/auth/shopify/callback",
  "https://pig-striking-snipe.ngrok-free.app/api/auth/callback",
  "https://pig-striking-snipe.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "discount-spotlight.myshopify.com"
