# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Tealium Track App"
client_id = "77ab0f117b5c21f97449cc51920fad19"
application_url = "https://nodejs.luckimediadevelopment.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_price_rules"
use_legacy_install_flow = true 

[auth]
redirect_urls = [
  "https://nodejs.luckimediadevelopment.com/auth/callback",
  "https://nodejs.luckimediadevelopment.com/auth/shopify/callback",
  "https://nodejs.luckimediadevelopment.com/api/auth/callback",
  "https://nodejs.luckimediadevelopment.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lm-ai-seo-metatag-enhancer-store.myshopify.com"
