type = "web_pixel_extension"
name = "DS-web-pixel"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.accountID]
name = "2924"
description = "My Birthday"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
